# -*- coding: utf-8 -*-
"""Mini_Shop_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gi8iEeJSUpGW9o-OLrdqAXsU6YrwHwsL
"""

"""
MINI SHOP MANAGEMENT SYSTEM
--------------------------------
A simple menu-driven Python program to help a small shop owner
add products, view them, search, sell items, check low stock,
and see a sales summary.

Python concepts demonstrated:
- while loop (menu), for loop (display), nested loop (bill/report),
  break, continue, pass
- functions with parameters, return values, and local/global scope
- list, tuple, dictionary, set
- list comprehension, dictionary comprehension
- lambda function
- recursion
- basic input validation
"""

# ---------------------------------------------------------
# GLOBAL DATA STRUCTURES
# ---------------------------------------------------------

# Dictionary -> stores all product information
# Structure: { "P101": {"name": "Notebook", "price": 250, "quantity": 20} }
products = {}

# List -> keeps a record of every sale made (each sale is a dict)
sales_records = []

# Tuple -> fixed shop categories (does not change while program runs)
categories = ("Stationery", "Electronics", "Grocery")

# Set -> will store the unique categories actually used by products added
used_categories = set()


# ---------------------------------------------------------
# FUNCTION: add_product
# ---------------------------------------------------------
def add_product():
    """Ask the shopkeeper for product details and store them."""
    product_id = input("Enter Product ID: ").strip().upper()

    # continue-style guard: don't allow duplicate IDs
    if product_id in products:
        print("Warning: A product with this ID already exists!\n")
        return  # exit function early (demonstrates a return value of None)

    name = input("Enter Product Name: ").strip()

    # Basic invalid-input handling for price and quantity
    try:
        price = float(input("Enter Price: "))
        quantity = int(input("Enter Quantity: "))
    except ValueError:
        print("Error: Invalid price or quantity. Product not added.\n")
        return

    print("Choose a category:")
    for i, cat in enumerate(categories, start=1):
        print(f"  {i}. {cat}")
    try:
        cat_choice = int(input("Enter category number: "))
        category = categories[cat_choice - 1]
    except (ValueError, IndexError):
        category = "Uncategorized"

    # Store product info using a dictionary
    products[product_id] = {
        "name": name,
        "price": price,
        "quantity": quantity,
        "category": category
    }

    # Add to the set of used categories (sets automatically avoid duplicates)
    used_categories.add(category)

    print("Product added successfully!\n")


# ---------------------------------------------------------
# FUNCTION: view_products
# ---------------------------------------------------------
def view_products():
    """Display all products currently in the shop using a for loop."""
    print("\n========== PRODUCTS ==========")

    if not products:
        print("No products available yet.\n")
        return

    # for loop -> display products
    for pid, info in products.items():
        print(f"\nID: {pid}")
        print(f"Name: {info['name']}")
        print(f"Price: Rs: {info['price']}")
        print(f"Stock: {info['quantity']}")
        print(f"Category: {info['category']}")
    print()


# ---------------------------------------------------------
# FUNCTION: search_product (by ID) -> returns product info or None
# ---------------------------------------------------------
def search_product(product_id):
    """
    Search for a product by its ID.
    Parameter: product_id (string)
    Return value: the product dictionary if found, otherwise None
    """
    product_id = product_id.strip().upper()
    if product_id in products:
        return products[product_id]
    return None


def search_by_name(keyword):
    """Bonus helper: search products whose name contains the keyword."""
    keyword = keyword.lower()
    # Dictionary comprehension: build a filtered dict of matches
    matches = {pid: info for pid, info in products.items()
               if keyword in info["name"].lower()}
    return matches


# ---------------------------------------------------------
# FUNCTION: sell_product
# ---------------------------------------------------------
def sell_product():
    """Sell a product: check stock, reduce it, and print a bill."""
    product_id = input("Enter Product ID: ").strip().upper()
    info = search_product(product_id)

    if info is None:
        print("Product not found!\n")
        return

    try:
        qty = int(input("Enter Quantity: "))
    except ValueError:
        print("Error: Invalid quantity entered.\n")
        return

    if qty <= 0:
        print("Error: Quantity must be greater than zero.\n")
        return

    if qty > info["quantity"]:
        print(f"Error: Not enough stock! Only {info['quantity']} left.\n")
        return

    total = qty * info["price"]
    info["quantity"] -= qty  # reduce stock

    # Record the sale (list of dictionaries)
    sales_records.append({
        "product_id": product_id,
        "name": info["name"],
        "quantity": qty,
        "total": total
    })

    # Print the bill
    print("\n========== BILL ==========")
    print(f"Product: {info['name']}")
    print(f"Quantity: {qty}")
    print(f"Price: Rs: {info['price']}")
    print(f"Total: Rs: {total}")
    print("Sale completed!\n")


# ---------------------------------------------------------
# FUNCTION: low_stock (uses LIST COMPREHENSION)
# ---------------------------------------------------------
def low_stock(threshold=5):
    """Return a list of products whose stock is below the threshold."""
    # List comprehension -> find low-stock products
    low_items = [(info["name"], info["quantity"])
                 for info in products.values() if info["quantity"] < threshold]
    return low_items


def show_low_stock():
    items = low_stock()
    print("\nLOW STOCK PRODUCTS")
    if not items:
        print("All products are sufficiently stocked.\n")
        return
    for name, qty in items:
        print(f"{name} - {qty} remaining")
    print()


# ---------------------------------------------------------
# FUNCTION: sales_summary
# ---------------------------------------------------------
def sales_summary():
    """Calculate and display total items sold and total sales amount."""
    total_items = 0
    total_amount = 0

    # Nested loop example: go through each sale, and within it,
    # "process" each unit sold (illustrates a nested loop use case)
    for sale in sales_records:
        for _unit in range(sale["quantity"]):
            total_items += 1
        total_amount += sale["total"]

    print("\n========== SALES SUMMARY ==========")
    print(f"Total Products Sold: {total_items}")
    print(f"Total Sales Amount: Rs. {total_amount:,}")
    print()

    return total_items, total_amount  # return multiple values (a tuple)


# ---------------------------------------------------------
# RECURSION: count total items in a list recursively
# ---------------------------------------------------------
def count_items_recursive(lst):
    """
    Recursively count how many elements are in a list.
    Base case: empty list -> 0
    Recursive case: 1 + count of the rest of the list
    """
    if not lst:          # base case
        return 0
    return 1 + count_items_recursive(lst[1:])


# ---------------------------------------------------------
# LAMBDA: sort products by price
# ---------------------------------------------------------
def show_products_sorted_by_price():
    """Bonus feature: display products sorted from cheapest to most expensive."""
    if not products:
        print("No products to sort.\n")
        return

    # Convert dict to a list of (id, info) tuples, then sort with a lambda
    product_list = list(products.items())
    sorted_products = sorted(product_list, key=lambda item: item[1]["price"])

    print("\nPRODUCTS SORTED BY PRICE (Low to High)")
    for pid, info in sorted_products:
        print(f"{info['name']} - Rs. {info['price']}")
    print()


# ---------------------------------------------------------
# DICTIONARY COMPREHENSION EXAMPLE
# ---------------------------------------------------------
def price_list():
    """Create a simple {name: price} dictionary using comprehension."""
    return {info["name"]: info["price"] for info in products.values()}


# ---------------------------------------------------------
# MAIN PROGRAM LOOP
# ---------------------------------------------------------
def main():
    menu_text = """
================================
     MINI SHOP SYSTEM
================================

1. Add Product
2. View Products
3. Search Product
4. Sell Product
5. Check Low Stock
6. Sales Summary
7. Sort Products by Price
8. Search by Name
9. Exit
"""

    # while loop -> keeps the menu running until the user exits
    while True:
        print(menu_text)
        choice = input("Enter your choice: ").strip()

        if choice == "":
            # continue -> skip empty input and show the menu again
            continue

        if choice == "1":
            add_product()
        elif choice == "2":
            view_products()
        elif choice == "3":
            pid = input("Enter Product ID: ").strip()
            result = search_product(pid)
            if result:
                print("\nProduct Found!")
                print(f"Name: {result['name']}")
                print(f"Price: Rs. {result['price']}")
                print(f"Stock: {result['quantity']}\n")
            else:
                print("Product not found!\n")
        elif choice == "4":
            sell_product()
        elif choice == "5":
            show_low_stock()
        elif choice == "6":
            sales_summary()
        elif choice == "7":
            show_products_sorted_by_price()
        elif choice == "8":
            keyword = input("Enter part of the product name: ").strip()
            found = search_by_name(keyword)
            if found:
                print("\nSEARCH RESULTS")
                for pid, info in found.items():
                    print(f"{pid}: {info['name']} - Rs. {info['price']}")
                print()
            else:
                print("No matching products found!\n")
        elif choice == "9":
            # Demonstrate recursion before exiting: total items ever sold
            all_quantities = [sale["quantity"] for sale in sales_records]
            total_sold_recursive = count_items_recursive(all_quantities)
            print(f"\nTotal sale entries processed: {total_sold_recursive}")
            print("Thank you for using Mini Shop System. Goodbye!")
            break  # break -> exits the while loop / ends the program
        else:
            print("Invalid choice, please try again.\n")
            pass  # pass -> placeholder, nothing extra needed here


# Run the program
if __name__ == "__main__":
    main()